version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=./config/local.yaml
    depends_on:
      - postgres
    restart: on-failure