# config/local.yaml

env: "local"
storage_path: "./storage/storage.db"
database_info:
    host: "postgres"
    port: "5432"
    username: "postgres"
    name: "postgres"
    password: "postgres"
http_server: 
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s
  user: "my_user"
  password: "my_pass"